interface notify {
    variant priority {
        default,
        normal,
        high
    }

    record notification {
        /// required
        to: list<string>,

        /// optional
        data: option<string>,
        title: option<string>,
        body: option<string>,
        ttl: option<u64>,
        expiration: option<u64>,
        priority: option<priority>,
        subtitle: option<string>,
        sound: option<string>,
        badge: option<u64>,
        channel-id: option<string>,
        category-id: option<string>,
        mutable-content: option<bool>,
    }

    record process-notif-config {
        /// process id to configure
        process: string,
        /// allow notifications
        allow: bool,
    }

    variant request {
        /// send a notification
        push(notification),
        /// history of notifications for given package
        history(string),
        /// change settings
        update-settings(process-notif-config),
    }

    variant response {
        /// notification sent
        push,
        /// history of notifications for given package
        history(list<notification>),
        /// settings for given package updated
        update-settings,
    }
}

world notify-sys-v0 {
    import notify;
    include process;
}
